name: baraanwilati
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  get: 4.6.6
  cached_network_image: ^3.3.1
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
  uses-material-design: true

